server:
  port: 8085
  servlet:
    context-path: /functionalities

springdoc:
  swagger-ui:
    path: /swagger-ui

spring:
  h2:
    console:
      enabled: true
      path: /h2-functionalities
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:file:./database/dbFile_functionalities;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    hibernate:
      ddl-auto: update #this configuration doesnt clean database after every restart
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true

management:
  endpoint:
    health:
      enabled: 'true'
  endpoints:
    enabled-by-default: 'false'

logging:
  file:
    path: /
    name: functionalities_logs.txt